CREATE TABLE customer_service (
id INT (11) NOT NULL AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
gender VARCHAR (10)  NOT NULL,
email VARCHAR (200) NOT NULL,
tel VARCHAR (15) NOT NULL,
location VARCHAR (200) NOT NULL,
service VARCHAR (200) NOT NULL,
items VARCHAR (20) NOT NULL,
requested_at DATETIME NOT NULL DEFAULT CURRENT_TIME,
PRIMARY KEY (id)

);